services:
    eb_core.service.mailer:
        class: EB\CoreBundle\Service\MailerService
        arguments: ["@mailer", "@twig"]

    eb_core.listener.notification:
        class: EB\CoreBundle\EventListener\NotificationListener
        arguments: ["@doctrine.orm.entity_manager", "@router", "@eb_core.service.mailer"]
        tags:
            - { name: kernel.event_subscriber }
