services:
    eb_core.service.mailer:
        class: EB\CoreBundle\Service\MailerService
        arguments: ["@mailer", "@twig"]

    eb_core.listener.notification:
        class: EB\CoreBundle\EventListener\NotificationListener
        arguments: ["@doctrine.orm.entity_manager", "@router", "@eb_core.service.mailer", "%main_domain%"]
        tags:
            - { name: kernel.event_subscriber }

    eb_core.twig_extension.notification:
        class: EB\CoreBundle\Twig\NotificationExtension
        arguments: ["@service_container"]
        tags:
            - { name: twig.extension }
