# FOSUserBundle configuration
fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: EB\UserBundle\Entity\AbstractUser
    service:
        user_manager: pugx_user_manager
    registration:
        confirmation:
            enabled: true
            from_email:
                address: registration@edua.com
                sender_name: EduA - Registration
        form:
            type: EB\UserBundle\Form\Type\RegistrationType
    resetting:
        email:
            from_email:
                address: resetting@edua.com
                sender_name: EduA - Resetting
    profile:
        form:
            type: EB\UserBundle\Form\Type\ProfileType
