# FOSUserBundle configuration
fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: EB\UserBundle\Entity\AbstractUser
    service:
        user_manager: pugx_user_manager
    registration:
        form:
            type: EB\UserBundle\Form\Type\RegistrationType
    profile:
        form:
            type: EB\UserBundle\Form\Type\ProfileType
