# PUGXMultiUserBundle configuration
pugx_multi_user:
    users:
        admin_user:
            entity:
                class: EB\UserBundle\Entity\AdminUser
        school_staff_user:
            entity:
                class: EB\UserBundle\Entity\SchoolStaffUser
        student_user:
            entity:
                class: EB\UserBundle\Entity\StudentUser
            registration:
                form:
                    type: EB\UserBundle\Form\Type\RegistrationStudentType
                    name: eb_user_registration_student
                    validation_groups: [Registration, Default]
                template: EBUserBundle:Registration:register_student.html.twig
