eb_core:
    resource: "@EBCoreBundle/Controller/"
    type:     annotation
    prefix:   /

eb_user:
    resource: "@EBUserBundle/Controller/"
    type:     annotation
    prefix:   /

# FOSUserBundle configuration
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
