<?php

namespace EB\CoreBundle\Twig;

use Doctrine\ORM\EntityManager;
use EB\CoreBundle\Entity\Notification;
use EB\UserBundle\Entity\AbstractUser;
use Symfony\Component\DependencyInjection\ContainerInterface;

class NotificationExtension extends \Twig_Extension
{
    /** @var  ContainerInterface $container */
    private $container;

    /**
     * @param ContainerInterface $container
     */
    public function __construct(ContainerInterface $container)
    {
        $this->container = $container;
    }

    /**
     * @return array
     */
    public function getFunctions()
    {
        return array(
            new \Twig_SimpleFunction('count_unread_notification', array($this, 'countUnreadNotification')),
            new \Twig_SimpleFunction('print_notif_text', array($this, 'printNotificationText')),
        );
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'eb_core_extension';
    }

    /**
     * @param AbstractUser $user
     * @return mixed
     */
    public function countUnreadNotification(AbstractUser $user)
    {
        /** @var EntityManager $em */
        $em = $this->container->get('doctrine')->getManager();
        $unreadNotificationNo = $em->getRepository('EBCoreBundle:Notification')->countUnreadByReceiverUser($user);

        return $unreadNotificationNo;
    }

    /**
     * @param Notification $notification
     * @return string
     * @throws \Exception
     */
    public function printNotificationText(Notification $notification)
    {
        $senderUser = $notification->getSenderUser();
        $senderUserName = $senderUser ? $senderUser->getFullName() : 'System';

        switch ($notification->getType()) {
            case Notification::TYPE_STUDENT_REGISTERED:
                // generated by the student and sent to the admin user
                $notifText = sprintf("<b>%s</b> has registered on EduA. You can verify his/her profile: ",
                    $senderUserName
                );
                break;
            case Notification::TYPE_STUDENT_ATTEND_ADMISSION:
                // generated by the student and sent to the Ssu user
                $notifText = sprintf("<b>%s</b> is attending one of your admissions on EduA for <b>%s</b>. You can verify his/her data: ",
                    $senderUserName,
                    $notification->getExtraData()['schoolName']
                );
                break;
            case Notification::TYPE_SSU_CONFIRM_STUDENT:
                // generated by the Ssu and sent to the student user
                $notifText = sprintf("<b>%s</b> accepted you to attend admission for school <b>%s</b>. You can see the admission: ",
                    $senderUserName,
                    $notification->getExtraData()['schoolName']
                );
                break;
            case Notification::TYPE_PRE_CLOSE_ADMISSION:
                $notifText = sprintf("<b>%s</b> generated notification. There is 1 day remaining until the admission for <b>%s</b> will end. You can update the admission status: ",
                    $senderUserName,
                    $notification->getExtraData()['schoolName']
                );
                break;
            default:
                throw new \Exception('Could not find notification with type: ' . $notification->getType());
        }

        return $notifText;
    }
}
