<?php

namespace EB\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AdmissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdmissionRepository extends EntityRepository
{
}
