<?php

namespace EB\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AdmissionAttendeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdmissionAttendeeRepository extends EntityRepository
{
}
