<?php

namespace EB\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use EB\CoreBundle\Entity\Admission;

/**
 * AdmissionAttendeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdmissionAttendeeRepository extends EntityRepository
{
    /**
     * @param Admission $admission
     * @return array
     */
    public function findByAdmission(Admission $admission)
    {
        $qb = $this->createQueryBuilder('aa');
        $qb->where('aa.admission = :admission')
            ->orderBy('aa.finalGrade', 'DESC')
            ->setParameter('admission', $admission)
        ;

        return $qb->getQuery()->getResult();
    }
}
