Feature: Admin
  In order to be able to make the application to be used by schools
  As an admin user
  I need to be able to create schools and school staff users

  Background:
    Given I am on "/"
    When I follow "Login"
    Then I should be on "/login"
    And I should see "Login"
    And I should see "Forgot your password?"
    When I fill in "username" with "emi.berea+admin-1@gmail.com"
    And I fill in "password" with "12345"
    And I press "Log in"
    Then I should be on "/admin/dashboard"
    And I should see "Admin dashboard"

  Scenario: As an admin, I want to create a new school
    When I follow "Schools"
    Then I should be on "/admin/school/"
    And I should see "School List"
    And I should see "Add School"
    When I follow "Add School"
    Then I should be on "/admin/school/new"
    And I should see "School Creation"
    When I fill in "Name" with "Faculty of Computer Science"
    And I fill in "Country" with "Romania"
    And I fill in "City" with "Iasi"
    And I fill in "Address" with "street General Berthelot 16"
    And I select "Faculty" from "Type"
    And I press "Create"
    Then I should see "New school created!"
    And I should see "Faculty of Computer Science"
    And I should see "Back to the list"
    When I follow "Back to the list"
    Then I should be on "/admin/school/"
    And I should see "School List"
    And I should see "Faculty of Computer Science"

  Scenario: As an admin, I want to create a new school staff user
    When I follow "School Staff Users"
    Then I should be on "/admin/school-staff/"
    And I should see "School Staff User List"
    And I should see "Add School Staff User"
    When I follow "Add School Staff User"
    Then I should be on "/admin/school-staff/new"
    And I should see "School Staff User Creation"
    When I fill in "Email" with "emi.berea+ssu-101@gmail.com"
    And I fill in "First name" with "SsuFn101"
    And I fill in "Last name" with "SsuLn101"
    And I fill in "Title" with "Mrs."
    And I fill in "Job title" with "Secretary"
    And I fill in "Academic degree" with "Bachelor"
    And I select "Facultatea de Informatica, Iasi" from "School"
    And I press "Create"
    Then I should see "New School Staff User created!"
    And I should see "emi.berea+ssu-101@gmail.com"
    And I should see "Back to the list"
    When I follow "Back to the list"
    Then I should be on "/admin/school-staff/"
    And I should see "School Staff User List"
    And I should see "emi.berea+ssu-101@gmail.com"

  Scenario: As an admin, I want to create a new student
    When I follow "Students"
    Then I should be on "/admin/student/"
    And I should see "Student List"
    And I should see "Add Student"
    When I follow "Add Student"
    Then I should be on "/admin/student/new"
    And I should see "Student Creation"
    When I fill in "Email" with "emi.berea+student-101@gmail.com"
    And I fill in "First name" with "StudentFn101"
    And I fill in "Last name" with "StudentLn101"
    And I fill in "Father initial" with "T"
    And I fill in "Pin" with "123456"
    And I fill in "City" with "Iasi"
    And I fill in "Address" with "street Carol I"
    And I fill in "High school" with "Moisil High School"
    And I fill in "Specialization" with "Computer Science"
    And I fill in "Baccalaureate average grade" with "8.5"
    And I fill in "Baccalaureate maximum grade" with "9.6"
    And I check "Enabled"
    And I check "Verified"
    And I press "Create"
    Then I should see "New student created!"
    And I should see "emi.berea+student-101@gmail.com"
    And I should see "Back to the list"
    When I follow "Back to the list"
    Then I should be on "/admin/student/"
    And I should see "Student List"
    And I should see "emi.berea+student-101@gmail.com"

  Scenario: As an admin, I want to assign a school staff user to a school
    When I follow "School Staff Users"
    Then I should be on "/admin/school-staff/"
    And I should see "School Staff User List"
    And I should see "emi.berea+ssu-1@gmail.com"
    When I follow "emi.berea+ssu-1@gmail.com"
    Then I should see "School Staff User"
    And I should see "Edit"
    When I follow "Edit"
    Then I should see "School Staff User Edit"
    When I select "Facultatea de Istorie, Iasi" from "School"
    And I press "Edit"
    Then I should see "School Staff User edited successfully!"
