Feature: School Staff User admission creation
  In order to be able to facilitate the attendance process for students
  As a School Staff User
  I need to be able to create an admission and make it available online

  Background:
    Given I am on "/"
    When I follow "Login"
    Then I should be on "/login"
    And I should see "Login"
    And I should see "Forgot your password?"
    When I fill in "username" with "emi.berea+ssu-1@gmail.com"
    And I fill in "password" with "12345"
    And I press "Log in"
    Then I should be on "/"
    And I should see "Edu Admission - Main page"

  Scenario: As a Ssu, I want to create a new admission then I logout and login as a student and attend the created admission
    When I follow "Admissions"
    Then I should be on "/school-staff/admission"
    And I should see "Admission List"
    And I should see "Add Admission"
    When I follow "Add Admission"
    Then I should be on "school-staff/admission/new"
    And I should see "Admission Creation"
    When I select "4" from "eb_core_admission_sessionDate_day"
    And I select "Jul" from "eb_core_admission_sessionDate_month"
    And I select "2017" from "eb_core_admission_sessionDate_year"
    And I fill in "Budget financed no" with "275"
    And I fill in "Fee payer no" with "90"
    And I press "Create"
    Then I should see "New admission created!"
    And I should see "04-07-2017"
    When I follow "Back to the list"
    Then I should be on "school-staff/admission"
    And I should see "Admission List"
    And I should see "04-07-2017"
    When I go to "/logout"
    Then I should be on "/"
    # As a student
    Given I am on "/"
    When I follow "Login"
    Then I should be on "/login"
    And I should see "Login"
    And I should see "Forgot your password?"
    When I fill in "username" with "emi.berea+student-1@gmail.com"
    And I fill in "password" with "12345"
    And I press "Log in"
    Then I should be on "/"
    And I should see "Edu Admission - Main page"
    When I follow "Open Admissions"
    Then I should be on "/student/open-admissions"
    And I should see "Open Admission List"
    When I follow "attend"
    Then I should see "Attend this admission with the following marks:"
    When I press "Attend"
    Then I should be on "/student/attended-admissions"
    And I should see "Attended Admissions by Student:"
