<?php

namespace EB\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SchoolStaffUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchoolStaffUserRepository extends EntityRepository
{
    /**
     * @return mixed
     */
    public function countAll()
    {
        $qb = $this->createQueryBuilder('ssu');
        $qb->select('count(ssu.id)');

        return $qb->getQuery()->getSingleScalarResult();
    }
}
