<?php

namespace EB\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StudentUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentUserRepository extends EntityRepository
{
    /**
     * @return mixed
     */
    public function countAll()
    {
        $qb = $this->createQueryBuilder('s');
        $qb->select('count(s.id)');

        return $qb->getQuery()->getSingleScalarResult();
    }
}
